### PR TITLE
Make wt-ui buildable and actually usable by 3rd party projects

### LINKED ISSUE #1: Publish to npm
We want this to be a library that can be easily imported in our apps and we want to use tags for npm releases, follow the same release structure than LifToken and wt-contracts repo.

### PR DESCRIPTION
**Pull request by JirkaChadima**
Hey, I've started on making the library actually usable in order to close #1 

1) I've updated webpack, babel and some other dependencies. That took in a newer build of storybook as well and the header layout got broken a little bit. (alpha 18 vs alpha 7)
2) I've changed what goes into the dist directory. It now contains built CSS, built JS, unbuilt JS (if anyone needs to build the components by themselves) and images (just copy-paste for now)
3) I've dropped react from the resulting JS build. It should be provided by the using app.

Can you have a look at 1, @skkr?

### CODE REVIEW

**Comment by JirkaChadima** [comment]
Even if we don't include the react components, we have to somehow include images referenced in the styles in the build.

**Comment by skkr** [comment]
@JirkaChadima the images used in the docs are from the media repo and are not attached to 
 the framework nor are required by the framework (so they could be replaced with other images if required). Is possible to import those images directly to any project as a dependency.  https://github.com/windingtree/media/tree/web-assets

Regarding your first bullet, it would be better if we can keep the current version of Storybook (at least by now), since Storybook doesn't provide a way to customize the UI (CSS classes), I had to use the elements attributes and values to identify them and apply the custom styles, so it will probably case issues if the markup changes.

**Comment by JirkaChadima** [comment]
Ad stroybook - I'll pin the current version and see how it goes.
Ad images - OK, I was mainly concerned with images lnked from css such as bg-header, but I see that's the only one that's used directly.

**Comment by JirkaChadima** [comment]
All in all, this is actually not necessary... If we are only exporting the css files, the only added value of this PR is the upgraded dependencies. Which we can always do later....

I'm closing this.

**Pull request closed without merging**
